apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-aws-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
stringData:
  credentials: |-
    [default]
    aws_access_key_id     = {{.Values.s3.accessKeyId}}
    aws_secret_access_key = {{.Values.s3.secretAccessKey}}

    [ami]
    aws_access_key_id     = {{.Values.ami.accessKeyId}}
    aws_secret_access_key = {{.Values.ami.secretAccessKey}}
  config: |-
    [default]
    output=json
  cli-params: --endpoint-url={{.Values.s3.endpointURL}}
  bucket-name: {{.Values.s3.bucketName}}
