apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-gcp-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
stringData:
  sa.json: {{ .Values.gcp.serviceAccountCredentialsJSON | quote }}
