version: 2.1
orbs:
  architect: giantswarm/architect@4.8.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          # executor: "app-build-suite" # uncomment this if you want automatic metadata generation and helm chart linting
          name: "package and push capi-image-builder chart"
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "capi-image-builder"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

  build:
    jobs:
      - architect/push-to-docker:
          context: "architect"
          name: push-capi-image-builder-to-quay
          image: "quay.io/giantswarm/capi-image-builder"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
