apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "name" . }}-capi-builder
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}

---

{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name" . }}-capi-builder
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames: ['{{ include "name" . }}-capi-builder']

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name" . }}-capi-builder
  labels:
    {{- include "labels.common" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "name" . }}-capi-builder
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "name" . }}-capi-builder
  namespace: {{ .Release.Namespace }}
---



apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name" . }}-affinity-assistant
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames: ['{{ include "name" . }}-affinity-assistant']

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name" . }}-affinity-assistant
  labels:
    {{- include "labels.common" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "name" . }}-affinity-assistant
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
---



{{- end }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "name" . }}-tekton-triggers-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "name" . }}-triggers-eventlistener-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "name" . }}-tekton-triggers-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name" . }}-triggers-eventlistener-clusterbinding
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "name" . }}-tekton-triggers-sa
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
