apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: capo-trigger-template
spec:
  params:
  - name: KUBERNETES_VERSION
    type: string
  resourcetmplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: build-capo-image-$(tt.params.KUBERNETES_VERSION)
    spec:
      timeouts:
        pipeline: "8h0m0s"
        tasks: "6h0m0s"
      pipelineRef:
        name: build-capo-image
      serviceAccountName: capi-builder
      params:
      - name: KUBERNETES_VERSION
        value: $(tt.params.KUBERNETES_VERSION)
      workspaces:
      - name: credentials
        secret:
          secretName: aws-credentials
      - name: output
        volumeClaimTemplate:
          metadata:
            name: capo-output-$(tt.params.KUBERNETES_VERSION)
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
