apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ include "name" . }}-capo-trigger-template
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  params:
  - name: KUBERNETES_VERSION
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-capo-image-$(tt.params.KUBERNETES_VERSION)-
    spec:
      timeouts:
        pipeline: "8h0m0s"
        tasks: "6h0m0s"
      pipelineRef:
        name: {{ include "name" . }}-build-capo-image
      serviceAccountName: {{ include "name" . }}-capi-builder
      params:
      - name: KUBERNETES_VERSION
        value: $(tt.params.KUBERNETES_VERSION)
      workspaces:
      - name: credentials
        secret:
          secretName: {{ include "name" . }}-aws-credentials
      - name: output
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
      - name: vars
        emptyDir: {}
