apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ include "name" . }}-check-kubernetes-versions
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  params: []
  resourcetmplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: trigger-capi-builds
    spec:
      pipelineRef:
        name: {{ include "name" . }}-trigger-capi-builds
      serviceAccountName: {{ include "name" . }}-capi-builder
