apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: {{ include "name" . }}-build-capi-images-event-listener
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    specific-provider-example-payload: |
      {
        "payload": "capg",
        "k8s": { "version": "1.2.3" }
      }
    all-providers-example-payload: |
      {
        "k8s": { "version": "1.2.3" }
      }
spec:
  serviceAccountName: {{ include "name" . }}-tekton-triggers-sa
  triggers:
    - name: build-capg-image
      interceptors:
      - ref:
          name: "cel"
        params:
        - name: "filter"
          value: has(body.provider) == false || body.provider == "capg"
      bindings:
      - ref: {{ include "name" . }}-capi-trigger-template-binding
      template:
        ref: {{ include "name" . }}-capg-trigger-template

    - name: build-capo-image
      interceptors:
      - ref:
          name: "cel"
        params:
        - name: "filter"
          value: has(body.provider) == false || body.provider == "capo"
      bindings:
      - ref: {{ include "name" . }}-capi-trigger-template-binding
      template:
        ref: {{ include "name" . }}-capo-trigger-template

---

apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: {{ include "name" . }}-trigger-capi-builds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  serviceAccountName: {{ include "name" . }}-tekton-triggers-sa
  triggers:
    - name: trigger-builds
      template:
        ref: {{ include "name" . }}-check-kubernetes-versions
