apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: {{ include "name" . }}-capi-trigger-template-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  params:
  - name: KUBERNETES_VERSION
    value: $(body.k8s.version)
