{{ if .Values.output.s3.enabled }}
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aws-cli

spec:
  workspaces:
    - name: source
      optional: true
    - name: secrets
      optional: true
      mountPath: /root/.aws
  params:
    - name: SCRIPT
      default: "aws $@"
    - name: ARGS
      default: ["help"]
  steps:
    - name: awscli
      image: docker.io/amazon/aws-cli:2.0.52@sha256:1506cec98a7101c935176d440a14302ea528b8f92fcaf4a6f1ea2d7ecef7edc4 #tag: 2.0.52
      script: "$(params.SCRIPT)"
      args:
        - "$(params.ARGS)"
{{ end }}