apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ include "name" . }}-s3-upload-image
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  description: "Take all built images in the `source` workspace and uploads it to an S3 bucket using details provided in the `credentials` workspace"
  params: []
  workspaces:
  - name: credentials
    mountPath: /root/.aws
    optional: false
  - name: source
    optional: false
  steps:
    - name: upload-image
      image: docker.io/amazon/aws-cli:2.0.52@sha256:1506cec98a7101c935176d440a14302ea528b8f92fcaf4a6f1ea2d7ecef7edc4 #tag: 2.0.52
      script: |
        set -x
        aws s3 $(cat $(workspaces.credentials.path)/cli-params) cp --recursive $(workspaces.source.path) s3://$(cat $(workspaces.credentials.path)/bucket-name)/
