apiVersion: v2
name: capi-image-builder
version: [[ .Version ]]
description: App to handle building of CAPI VM images for various providers
home: https://github.com/giantswarm/capi-image-builder
sources:
- https://github.com/some-org/some-repo
