# TEMPLATE-APP: This is set as a reasonable default, feel free to change.

name: capi-image-builder
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/capi-image-builder
  tag: v0.0.1
  pullPolicy: IfNotPresent


# Output where to check what needs to be built and where to upload the image
#  * Note *  Only 1 can be enabled at a time
output:
  s3:
    enabled: true
    accessKeyId:
    secretAccessKey:
    endPointUrl:
    bucketName:
    # The make target from this file
    #   https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/Makefile
    makeTarget: build-qemu-ubuntu-2004

  # TODO  
  # support the following output options
  gcp:
    enabled: false
    # The make target from this file
    #   https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/Makefile
    makeTarget: build-gce-ubuntu-2004
  openstackGlance:
    enabled : false
    # The make target from this file
    #   https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/Makefile
    makeTarget: build-qemu-ubuntu-2004


k8s:
  excludeVersions: 
  - v1.21.0 
  - v1.21.1 
  - v1.21.2 
  - v1.21.3 
  - v1.21.4 
  - v1.21.5 
  - v1.21.6 
  - v1.21.7 
  - v1.21.8 
  - v1.22.0 
  - v1.22.1 
  - v1.22.2 
  - v1.22.3 
  - v1.22.4 
  - v1.22.5 
  - v1.22.6 
  - v1.22.7 
  - v1.22.8 
  - v1.23.0 
  - v1.23.1 
  - v1.23.2 
  - v1.23.3 
  - v1.23.4 
  - v1.24.0-alpha.2 
  - v1.24.0-alpha.1 
  - v1.24.0-rc.1 
  - v1.24.0-rc.0 
  - v1.24.0-beta.0 
  - v1.24.0-alpha.3 
  - v1.24.0-alpha.4
  - v1.25.0-alpha.1 

# The following is to cleanup the k8s version detect scripts from this app
#  if tekton is already setup to cleanup jobs set below to false
tektonDetectCleaner:
  enable: true
