serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

s3:
  accessKeyId: ""
  secretAccessKey: ""
  endpointURL: ""
  bucketName: ""

gcp:
  serviceAccountCredentialsJSON: ""
