serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/capi-image-builder
  tag: 0.0.1

s3:
  image:
    registry: docker.io
    name: amazon/aws-cli
    tag: 2.0.52@sha256:1506cec98a7101c935176d440a14302ea528b8f92fcaf4a6f1ea2d7ecef7edc4
  accessKeyId: ""
  secretAccessKey: ""
  endpointURL: ""
  bucketName: ""

gcp:
  serviceAccountCredentialsJSON: ""
