# TEMPLATE-APP: This is set as a reasonable default, feel free to change.

name: capi-image-builder
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/capi-image-builder
  tag: v0.0.1
  pullPolicy: IfNotPresent
