---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ include "name" . }}-build-capg-image
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  params:
  - name: KUBERNETES_VERSION
    type: string
    description: "The Kubernetes version to build for - e.g. 1.24.3 (Note, if a `v` prefix is added, this will be stripped off in the build task)"
  workspaces:
  - name: credentials
    description: "GCP credentials containing the required `sa.json` file for authenticating"
    optional: false
  - name: vars
    description: "Shared workspace for passing vars betweeen task steps"
    optional: false
  - name: output
    description: "The location where VM images are saved to"
    optional: false
  tasks:
    - name: build-capi-image-ubuntu-1804
      timeout: 6h
      retries: 1
      taskRef:
        name: {{ include "name" . }}-build-capi-image
      params:
        - name: KUBERNETES_VERSION
          value: $(params.KUBERNETES_VERSION)
        - name: MAKE_TARGET
          value: "build-gce-ubuntu-1804"
        - name: ENV_VARS
          value: |
            export GCP_PROJECT_ID=giantswarm-vm-images
            export GOOGLE_APPLICATION_CREDENTIALS=/config/credentials/sa.json
      workspaces:
      - name: credentials
        workspace: credentials
      - name: output
        workspace: output
      - name: vars
        workspace: vars

    - name: build-capi-image-ubuntu-2004
      timeout: 6h
      retries: 1
      taskRef:
        name: {{ include "name" . }}-build-capi-image
      params:
        - name: KUBERNETES_VERSION
          value: $(params.KUBERNETES_VERSION)
        - name: MAKE_TARGET
          value: "build-gce-ubuntu-2004"
        - name: ENV_VARS
          value: |
            export GCP_PROJECT_ID=giantswarm-vm-images
            export GOOGLE_APPLICATION_CREDENTIALS=/config/credentials/sa.json
      workspaces:
      - name: credentials
        workspace: credentials
      - name: output
        workspace: output
      - name: vars
        workspace: vars

    - name: share-images
      taskRef:
        name: {{ include "name" . }}-share-capg-images
      runAfter:
        - build-capi-image-ubuntu-1804
        - build-capi-image-ubuntu-2004
      params:
        - name: KUBERNETES_VERSION
          value: $(params.KUBERNETES_VERSION)
      retries: 1
      workspaces:
      - name: credentials
        workspace: credentials
