apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ include "name" }}-trigger-capi-builds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  params: []
  workspaces: []
  tasks:
  - name: trigger-builds-from-kubernetes-releases
    retries: 1
    taskRef:
      name: {{ include "name" }}-trigger-builds-from-kubernetes-releases
